name: CI/CD Microservicio Inventario

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Dar permisos de ejecución a Maven Wrapper
      run: chmod +x ./mvnw

    - name: Compilar proyecto con Maven
      run: ./mvnw clean install -DskipTests